apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      name: celery-worker
  template:
    metadata:
      labels:
        name: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: coacher
          command:
            - "bash"
            - "-c"
            - "celery -A coacher.celery worker -l info"
          env:
            - name: CELERY_BROKER_URL
              value: "amqp://admin:secretpassword@rabbitmq.rabbitmq:5672"
            - name: CELERY_RESULT_BACKEND
              value: "db+postgresql://postgres:super-secret@postgres-service:5432/coacher"
            - name: SECRET_KEY
              value: "secret-key"
