apiVersion: v1
kind: Service
metadata:
  name: coacher-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: coacher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coacher
spec:
  selector:
    matchLabels:
      app: coacher
  template:
    metadata:
      labels:
        app: coacher
    spec:
      containers:
        - name: coacher
          image: coacher
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: postgres-configuration
        - name: coacher-nginx
          image: coacher-nginx
          ports:
            - containerPort: 8080
      initContainers:
        - name: init-coacher-container
          image: busybox:1.28
          # Ugly hack to wait for fixed time before starting Django
          command: ["sh", "-c", "echo Sleeping... && sleep 1 && echo Done."]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: coacher-migrations
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: coacher-migration
          image: coacher
          command: ["python", "manage.py", "migrate"]
          env:
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: postgres-configuration
      restartPolicy: Never
