FROM python:3.8.14-slim-buster
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput
CMD ["gunicorn", "coacher.wsgi"]
